#path for upload files (menu position pic for example)
#!!!!!! PATH must be outside project
upload.path: ${UPLOAD_PATH:C:\Users\JDubo\project}

spring:
  application:
    name: crm-backend
  http:
    thymeleaf:
      encoding: UTF-8
      servlet:
        content-type: text/html;charset=UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true
  datasource:
#    url: jdbc:postgresql://localhost:5432/catering
    url: jdbc:postgresql://localhost:5555/catering
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_POOL_SIZE:1}
      idle-timeout: ${DB_IDLE_TIMEOUT_MS:60000}
      connection-timeout: ${DB_CONNECTION_TIMEOUT_MS:90000}
      max-lifetime: ${DB_MAX_CONN_LIFETIME_MS:300000}
      pool-name: MasterCP-1
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true